### PR TITLE
Replace HTML scraper with JSON schema transformation

### PR DESCRIPTION
**Pull request by mweagle**
## BREAKING CHANGE

Replaced the HTML based scraper with one that uses a schema published from: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html

While it does preserve the JSON roundtrip behavior, it does change the public typenames of both properties and public structs. LMK your thoughts - thanks.

Usage: 
`go generate` or `go test -v ./scraper/.`

I'm not sure why Travis is failing - in local testing I see:
```
mweagle@Matts-MBP go-cloudformation (master)$ go test -v .
=== RUN   TestCustomResource
--- PASS: TestCustomResource (0.00s)
=== RUN   TestRoundtrips
--- PASS: TestRoundtrips (0.02s)
=== RUN   Test
OK: 22 passed
--- PASS: Test (0.00s)
PASS
ok  	github.com/mweagle/go-cloudformation	0.030s
```

Related: 
 * https://github.com/crewjam/go-cloudformation/issues/19
 * https://github.com/crewjam/go-cloudformation/issues/21
 * https://github.com/crewjam/go-cloudformation/issues/9

### CODE REVIEW

**Comment by pwaller** [comment]
> LMK your thoughts - thanks

Do it! :) Also, I wish I had discovered this years ago. Looks good. Also, you should know Amazon [have now created their own equivalent](https://github.com/awslabs/goformation/issues/31), but it's [not as powerful](https://github.com/awslabs/goformation/issues/31), yet.

**Comment by mweagle** [comment]
Hi @pwaller - thanks for the feedback. I've pushed up a new version to track the August 23, 2017 CloudFormation release. The AWS version is something to keep an eye on. Thanks again to @crewjam for doing all the heavy lifting here :)

**Comment by mikkeloscar** [comment]
@mweagle awesome stuff, thanks for keeping this up to date!

**Comment by mweagle** [comment]
Pushed a new version to keep up with the latest schema. Ross has gracious offered me collaborator status to help support this repo as well. I would like to merge this PR into main to keep up to date with the JSON spec, but am leery of introducing breaking changes without some sort of notice.

Any thoughts from repo consumers?

**Comment by mikkeloscar** [comment]
For me backward compatibility wouldn't matter, I think it's more important to get this up to date with latest versions of Cloudformation.

However, one way to make the upgrade (or non-upgrade) simpler for other consumers could be to tag a release before these changes are included and one after, so people easily can pin the dependency to the previous (current) version if desired.

**Comment by mweagle** [comment]
Ok - thinking of tagging with 0.9 and then following up with a 1.0 tagged from the JSON definition. Sound like a plan?

**Comment by mikkeloscar** [comment]
Sounds good to me!

**Comment by mweagle** [comment]
Getting back to this - planning on tagging this weekend and then belatedly merging the PR which I've been trying to keep up to date. Please reply if you foresee issues.

**Comment by mweagle** [comment]
Merging - please pin to https://github.com/crewjam/go-cloudformation/releases/tag/0.99 if you require backwards compatible types.

**Pull request merged**
